{% set name = "tblib" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tblib-{{ version }}.tar.gz
  sha256: a6df30f272c08bf8be66e0775fad862005d950a6b8449b94f7c788731d70ecd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - tblib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ionelmc/python-tblib
  doc_url: https://python-tblib.readthedocs.io/en/latest/
  summary: Traceback serialization library.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - jrbourbeau
    - xhochy
