{% set name = "tblib" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tblib-{{ version }}.tar.gz
  sha256: 93622790a0a29e04f0346458face1e144dc4d32f493714c6c3dff82a4adb77e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - tblib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ionelmc/python-tblib
  doc_url: https://python-tblib.readthedocs.io/en/latest/
  summary: Traceback serialization library.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jrbourbeau
    - xhochy
