{% set name = "tblib" %}
{% set version = "2.0.0" %}
{% set compress_type = "tar.gz" %}
{% set hash = "a6df30f272c08bf8be66e0775fad862005d950a6b8449b94f7c788731d70ecd7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - tblib

about:
  home: https://github.com/ionelmc/python-tblib
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: Traceback serialization library.
  dev_url: https://github.com/ionelmc/python-tblib
  doc_url: https://python-tblib.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jrbourbeau
