schema_version: 1

context:
  name: tblib
  version: 3.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tblib-${{ version }}.tar.gz
  sha256: 846e274d0aeec822953251a3cbd3d840fd0ee7a5ec844d59ffbde7b056f9cd2b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - tblib

about:
  summary: Traceback serialization library.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/ionelmc/python-tblib
  documentation: https://python-tblib.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jrbourbeau
    - xhochy
