travis:
  secure:
    BINSTAR_TOKEN: gT/xFsk9IWtLH3rbR9Jww/hr8ISD06GowbbvjjLDGGGuPr6BROeOzRhkhLjAyVmzTvonkavcxTRQUYzwQ3DvrimslVIy7cXabXe+MjgA31+gEK9L93fetEFgVI4HK76IPc1N3an9ZJ77aCheGJLzs2la2voLlNTrDz3pUBT5LOMSCSd4Cnoebg2AbDbLbtG8b3RBphSg03cWvHlF1MQfssl3iftHG7/ZRP7nkfav8H4i/jC/+EqOg4STLsHYRWJ2CzL7edUbO5R9XBXFP4wdkL0BDTAXc466eb8vZ0+MkZMMaIMxWtc836Xd4pHcg/xPXqixSvybrfKgBPC4Kask9CWftZvhl546i6R9ES1O1NxZv/6IhZ18d/ALYGOPngjDLVp5rUz5gnB+ZHKPC6F07K2tPAATGZfbde/MDQRS3aUymnupSx/kiCSpdWYy8n/5ucf694JdfGJ3XoBrprq0f/xcgUwrGt0+e+iugcqXPNk455xhVMcZP3ljkipM8oC2/KgMwlHFYC5AZVDk/zsljnvli+QDFbnyJYseE5lUT0jpN+QAq9wkFd7rvT20t8tyJyHUB2VzAxHuip3QX3kEruMLmSBHa830kgzOq5E9C6GL6T5uok5DGjAvDTdmC7A+YxThNmj+IEghqA8r6zz1Jzubb7NdSk8/rZOQR7dQRRE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
